"""conftest.py - Auto-generated by pytest-api-cov init"""

import pytest

# Import your FastAPI app
from main import main


@pytest.fixture
def app():
    """Provide the FastAPI app for API coverage testing."""
    return main
