"""conftest.py - Auto-generated by pytest-api-cov init"""

import pytest

# Import your FastAPI app
from example.app import app


@pytest.fixture
def app():  # noqa: F811
    """Provide the FastAPI app for API coverage testing."""
    return app
