"""CLI commands for setup and configuration."""

import argparse


def generate_conftest_content(framework: str, file_path: str, app_variable: str) -> str:
    """Generate example conftest.py content for a given framework."""
    module_path = file_path.replace("/", ".").replace("\\", ".").replace(".py", "")

    if framework == "FastAPI":
        test_client_import = "from fastapi.testclient import TestClient"
        client_creation = "return TestClient(app)"
    elif framework == "Flask":
        test_client_import = "from flask.testing import FlaskClient"
        client_creation = "return FlaskClient(app)"
    else:
        test_client_import = ""
        client_creation = "# Create and return a test client for your framework"

    return f'''"""conftest.py - Example generated by pytest-api-cov CLI"""

import pytest
{test_client_import}

from {module_path} import {app_variable} as app


@pytest.fixture
def client():
    """Test client fixture for {framework}."""
    {client_creation}


# Use the coverage_client fixture in your tests:
# def test_endpoint(coverage_client):
#     response = coverage_client.get("/endpoint")
#     assert response.status_code == 200
'''


def generate_pyproject_config() -> str:
    """Generate example pyproject.toml configuration section."""
    return """
# pytest-api-cov configuration
[tool.pytest_api_cov]
# Fail if coverage is below this percentage (optional)
# fail_under = 80.0

# Show different endpoint types in report
show_uncovered_endpoints = true
show_covered_endpoints = false
show_excluded_endpoints = false

# Exclude endpoints matching these patterns (optional)
# exclusion_patterns = [
#     "*/health",
#     "*/metrics",
#     "*/docs/*",
# ]

# Save JSON report to file (optional)
# report_path = "api_coverage.json"

# Force Unicode symbols in terminal output (optional)
# force_sugar = true

# Specify custom client fixture names to discover (optional)
# client_fixture_names = ["client", "test_client", "my_custom_client"]

# Group HTTP methods by endpoint for legacy behavior (optional)
# group_methods_by_endpoint = false
"""


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(prog="pytest-api-cov", description="pytest API coverage plugin CLI tools")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    subparsers.add_parser("show-pyproject", help="Print example pyproject.toml configuration")
    show_conftest = subparsers.add_parser("show-conftest", help="Print example conftest content")
    show_conftest.add_argument("framework", nargs=1, help="Framework name (FastAPI|Flask)")
    show_conftest.add_argument("module_path", nargs=1, help="Module path of your app, e.g. src.main")
    show_conftest.add_argument("app_variable", nargs=1, help="App variable name in the module, e.g. app")

    args = parser.parse_args()

    if args.command == "show-pyproject":
        print(generate_pyproject_config())
        return 0

    if args.command == "show-conftest":
        framework = args.framework[0]
        module_path = args.module_path[0]
        app_variable = args.app_variable[0]
        print(generate_conftest_content(framework, module_path + ".py", app_variable))
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    import sys

    sys.exit(main())
